server:
  port: 1234

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: management-ops
          uri: lb://management-ops
          predicates:
            - Path=/console/**
            - Path=/dashboard/**
        - id: discovery-server
          uri: http://localhost:8761/eureka-web
          predicates:
            - Path=/eureka-web/**
            - Path=/eureka/**
          filters:
            - SetPath=/eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  instance:
    hostname: localhost
    prefer-ip-address: true
