server:
  port: 1234

spring:
  profiles:
    active: dev
datasource:
  url: jdbc:postgresql://localhost:5432/my_school
  username: root
  password: 1234
  driverClassName: org.postgresql.Driver
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: upgrade
  show-sql: true
flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    cleanDisabled: false

---

spring:
  profiles:
    active: test
datasource:
  url: jdbc:postgresql://localhost:5432/my_school
  username: root
  password: 1234
  driverClassName: org.postgresql.Driver
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: upgrade
  show-sql: true
flyway:
  enabled: true
  schemas: public
  locations: classpath:db/migration
  cleanDisabled: false

---

spring:
  profiles:
    active: prod
datasource:
  url: jdbc:postgresql://localhost:5432/my_school
  username: root
  password: 1234
  driverClassName: org.postgresql.Driver
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: upgrade
  show-sql: true
flyway:
  enabled: true
  schemas: public
  locations: classpath:db/migration
  cleanDisabled: false