server:
  port: 1234

spring:
  datasource:
    url: jdbc:postgresql://my-school.cqkytc8dhq8x.ap-south-1.rds.amazonaws.com:5432/my_school
    username: root
    password: root1234
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    cleanDisabled: false

logging:
  level:
    org:
      springframework: INFO
      hibernate: DEBUG
    com:
      myschool: INFO