server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka
      password: password

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka_uri:http://eureka:password@localhost:8761/eureka}
  instance:
    hostname: localhost

logging:
  level:
    com:
      netflix:
        eureka: debug