server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka
      password: password

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
  dashboard:
    path: /eureka-web

logging:
  level:
    com:
      netflix:
        eureka: debug